In [23]:
import nltk

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [3]:
from nltk.corpus import brown

In [4]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [5]:
data = brown.sents(categories = 'adventure')

In [6]:
print(data)

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]


In [7]:
len(data)

4637

In [9]:
' '.join(data[4])

'But all of this was rationalization .'

In [24]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [25]:
document = """It was a very pleasant day. The weather was cool and there were light showers.
I went to the market to buy some fruits."""

sentence = "Send all the 50 documents related to chapters 1,2,3 at thelokeshgoel00@gmail.com"

In [26]:
sents = sent_tokenize(document)
print(sents)

['It was a very pleasant day.', 'The weather was cool and there were light showers.', 'I went to the market to buy some fruits.']


In [5]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/insanenerd/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [7]:
print(len(sents))

3


In [8]:
sentence.split()

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'thelokeshgoel00@gmail.com']

In [27]:
words = word_tokenize(sentence)

In [28]:
print(words,len(words))

['Send', 'all', 'the', '50', 'documents', 'related', 'to', 'chapters', '1,2,3', 'at', 'thelokeshgoel00', '@', 'gmail.com'] 13


In [29]:
from nltk.corpus import stopwords

In [30]:
sw = set(stopwords.words('english'))

In [31]:
def remove_stopwords(text,stopwords):
    useful_words = [w for w in text if w not in stopwords]
    return useful_words

In [32]:
text = "i am not bothered about her very much".split()
useful_text = remove_stopwords(text, sw)
print(useful_text)

['bothered', 'much']


In [33]:
from nltk.tokenize import RegexpTokenizer

In [34]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')
useful_text = tokenizer.tokenize(sentence)

In [35]:
print(useful_text)

['Send', 'all', 'the', 'documents', 'related', 'to', 'chapters', 'at', 'thelokeshgoel', '@gmail.com']


In [36]:
text = """Foxes love to make jumps. The quick brown fox was seen jumping over the
lovely dog from a 6ft high wall"""

In [37]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [24]:
ps = PorterStemmer()

In [25]:
ps.stem('jumping')

'jump'

In [26]:
ps.stem('jumps')

'jump'

In [28]:
ps.stem('loving')

'love'

In [29]:
ss = SnowballStemmer('english')

In [38]:
ps.stem('Jumving')

'jumv'

# Lemmnatization

In [38]:
from nltk.stem import WordNetLemmatizer

wn = WordNetLemmatizer()


In [44]:
wn.lemmatize('love')

'love'

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
countv = CountVectorizer()

In [6]:
corpus = [
    'Indian cricket team will win World Cup, says Capt. Virat Kohli. World cup will be held in Sri Lanka',
    'We will win next Lok Sabha Elections, says confident Indian PM',
    'The nobel laurste won the hearts of the people.',
    'The movie Raazi is an exciting Inddian Spy thriller bassed upon a real story.'
]

In [7]:
vectorized_corpus = countv.fit_transform(corpus)

In [9]:
print(vectorized_corpus.toarray())

[[0 0 1 1 0 1 2 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0
  1 0 2 1 0 2]
 [0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0
  0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 3 0 0
  0 0 0 0 1 0]
 [1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 1
  0 0 0 0 0 0]]


In [10]:
vectorized_corpus = vectorized_corpus.toarray()

In [11]:
countv.vocabulary_

{'indian': 13,
 'cricket': 5,
 'team': 32,
 'will': 38,
 'win': 39,
 'world': 41,
 'cup': 6,
 'says': 28,
 'capt': 3,
 'virat': 36,
 'kohli': 15,
 'be': 2,
 'held': 10,
 'in': 11,
 'sri': 30,
 'lanka': 16,
 'we': 37,
 'next': 20,
 'lok': 18,
 'sabha': 27,
 'elections': 7,
 'confident': 4,
 'pm': 24,
 'the': 33,
 'nobel': 21,
 'laurste': 17,
 'won': 40,
 'hearts': 9,
 'of': 22,
 'people': 23,
 'movie': 19,
 'raazi': 25,
 'is': 14,
 'an': 0,
 'exciting': 8,
 'inddian': 12,
 'spy': 29,
 'thriller': 34,
 'bassed': 1,
 'upon': 35,
 'real': 26,
 'story': 31}

In [12]:
len(vectorized_corpus[0])

42

In [13]:
len(countv.vocabulary_.keys())

42

In [14]:
countv.inverse_transform(vectorized_corpus[2])

[array(['hearts', 'laurste', 'nobel', 'of', 'people', 'the', 'won'],
       dtype='<U9')]

In [18]:
CountVectorizer['tokenizer']?

SyntaxError: invalid syntax (<ipython-input-18-602ca8d3d213>, line 1)

In [40]:
def myTokenizer(document):
    words = tokenizer.tokenize(document.lower())
    
    words = remove_stopwords(words,sw)
    return words

In [41]:
myTokenizer(sentence)

['send', 'documents', 'related', 'chapters', 'thelokeshgoel', '@gmail.com']

In [42]:
cv = CountVectorizer(tokenizer = myTokenizer)

In [43]:
vectorized_corpus = cv.fit_transform(corpus).toarray()

In [44]:
print(vectorized_corpus)

[[0 1 0 1 2 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 2]
 [0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0]]


In [45]:
len(vectorized_corpus[0])

33

In [46]:
cv.inverse_transform(vectorized_corpus)

[array(['capt.', 'cricket', 'cup', 'held', 'indian', 'kohli.', 'lanka',
        'says', 'sri', 'team', 'virat', 'win', 'world'], dtype='<U9'),
 array(['confident', 'elections', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'win'], dtype='<U9'),
 array(['hearts', 'laurste', 'nobel', 'people.'], dtype='<U9'),
 array(['bassed', 'exciting', 'inddian', 'movie', 'raazi', 'real', 'spy',
        'story.', 'thriller', 'upon'], dtype='<U9')]

In [47]:
test_corpus = [
    'Indian cricket team rock!'
]

In [49]:
cv.transform(test_corpus).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [50]:
cv.vocabulary_

{'indian': 10,
 'cricket': 3,
 'team': 27,
 'win': 31,
 'world': 32,
 'cup': 4,
 'says': 23,
 'capt.': 1,
 'virat': 30,
 'kohli.': 11,
 'held': 8,
 'sri': 25,
 'lanka': 12,
 'next': 16,
 'lok': 14,
 'sabha': 22,
 'elections': 5,
 'confident': 2,
 'pm': 19,
 'nobel': 17,
 'laurste': 13,
 'hearts': 7,
 'people.': 18,
 'movie': 15,
 'raazi': 20,
 'exciting': 6,
 'inddian': 9,
 'spy': 24,
 'thriller': 28,
 'bassed': 0,
 'upon': 29,
 'real': 21,
 'story.': 26}

In [51]:
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function myTokenizer at 0x7f25eb2f10d0>,
                vocabulary=None)

In [54]:
cv.transform?

In [57]:
cv = CountVectorizer(ngram_range=(2,2))

In [59]:
cv.fit_transform(sentence).toarray()

ValueError: Iterable over raw text documents expected, string object received.

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [61]:
tfidf = TfidfVectorizer()

In [67]:
vc = tfidf.fit_transform(corpus).toarray()

In [68]:
vc

array([[0.46333427, 0.59662724, 0.46333427, 0.        , 0.46333427,
        0.        ],
       [0.41285857, 0.        , 0.41285857, 0.        , 0.41285857,
        0.69903033],
       [0.3645444 , 0.46941728, 0.3645444 , 0.61722732, 0.3645444 ,
        0.        ]])

In [69]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}

In [66]:
corpus = ["this is good movie", "This was good movie", "this is not good movie"]